<?php
$GLOBALS['gLang']['lang_passport']['user'] = '帐号';
$GLOBALS['gLang']['lang_passport']['pwd'] = '密码';
$GLOBALS['gLang']['lang_passport']['validatecode'] = '验证码';
$GLOBALS['gLang']['lang_passport']['anotherone'] = '换一张';
$GLOBALS['gLang']['lang_passport']['notclear'] = '看不清';
$GLOBALS['gLang']['lang_passport']['autologin'] = '记住我';
$GLOBALS['gLang']['lang_passport']['signon'] = '登录';
$GLOBALS['gLang']['lang_passport']['signup'] = '注册';
$GLOBALS['gLang']['lang_passport']['forgetpwd'] = '忘记密码';
$GLOBALS['gLang']['lang_passport']['emailorusername'] = '用户邮箱/用户名';
$GLOBALS['gLang']['lang_passport']['helpmsg1'] = '请输入您的帐号!';
$GLOBALS['gLang']['lang_passport']['helpmsg2'] = '请输入您的密码!';
$GLOBALS['gLang']['lang_passport']['usernotexist'] = '此用户不存在!';
$GLOBALS['gLang']['lang_passport']['codeinvalid'] = "验证码错误!";
$GLOBALS['gLang']['lang_passport']['illegalsignon'] = "非法登录!";
$GLOBALS['gLang']['lang_passport']['pwdwrong'] = "密码错误!";
$GLOBALS['gLang']['lang_passport']['userforbidden'] = "此用户被禁止登录!";
$GLOBALS['gLang']['lang_passport']['invalidurl'] = "无效地址!";
$GLOBALS['gLang']['lang_passport']['regbyusername'] = "采用用户名注册";
$GLOBALS['gLang']['lang_passport']['regbyemail'] = "采用电子邮箱注册";
$GLOBALS['gLang']['lang_passport']['email'] = "电子邮箱";
$GLOBALS['gLang']['lang_passport']['username'] = "用户名";
$GLOBALS['gLang']['lang_passport']['comfirmpwd'] = "确认密码";
$GLOBALS['gLang']['lang_passport']['pwdquestion'] = "密码保护问题";
$GLOBALS['gLang']['lang_passport']['selectaquestion'] = "请选择一个问题";
$GLOBALS['gLang']['lang_passport']['q1'] = "我就读的第一所学校的名称？";
$GLOBALS['gLang']['lang_passport']['q2'] = "我最喜欢的休闲运动是什么？";
$GLOBALS['gLang']['lang_passport']['q3'] = "我最喜欢的运动员是谁？";
$GLOBALS['gLang']['lang_passport']['q4'] = "我最喜欢的物品的名称？";
$GLOBALS['gLang']['lang_passport']['q5'] = "我最喜欢的歌曲？";
$GLOBALS['gLang']['lang_passport']['q6'] = "我最喜欢的食物？";
$GLOBALS['gLang']['lang_passport']['q7'] = "我最爱的人的名字？";
$GLOBALS['gLang']['lang_passport']['q8'] = "我最爱的电影？";
$GLOBALS['gLang']['lang_passport']['q9'] = "我妈妈的生日？";
$GLOBALS['gLang']['lang_passport']['q10'] = "我的初恋日期？";
$GLOBALS['gLang']['lang_passport']['youranswer'] = "您的答案";
$GLOBALS['gLang']['lang_passport']['realname'] = "姓名";
$GLOBALS['gLang']['lang_passport']['nickname'] = "昵称";
$GLOBALS['gLang']['lang_passport']['sex'] = "性别";
$GLOBALS['gLang']['lang_passport']['boy'] = "男";
$GLOBALS['gLang']['lang_passport']['girl'] = "女";
$GLOBALS['gLang']['lang_passport']['reset'] = "重置";
$GLOBALS['gLang']['lang_passport']['back'] = "返回";
$GLOBALS['gLang']['lang_passport']['userexist'] = "此帐号已经存在！请换一个";
$GLOBALS['gLang']['lang_passport']['userisok'] = "此帐号可用！";
$GLOBALS['gLang']['lang_passport']['insertpwd'] = "输入密码！";
$GLOBALS['gLang']['lang_passport']['insertemail'] = "请输入有效邮箱！";
$GLOBALS['gLang']['lang_passport']['usernamerule'] = "用户名只能由3-15位字母(a-z)、数字(0-9)或下划线(_)构成,  并且只能以字母开头！";
$GLOBALS['gLang']['lang_passport']['pwdnotsame'] = "两个密码不一致！";
$GLOBALS['gLang']['lang_passport']['nicknamerule'] = "昵称不能为空，长度在2-8个字";
$GLOBALS['gLang']['lang_passport']['sexrule'] = "请选择性别！";
$GLOBALS['gLang']['lang_passport']['submit'] = "提交";
$GLOBALS['gLang']['lang_passport']['registered'] = "祝贺！您已经成功注册！";
$GLOBALS['gLang']['lang_passport']['yourquestion'] = "您的密码保护问题";
$GLOBALS['gLang']['lang_passport']['youranswer'] = "请输入您的答案";
$GLOBALS['gLang']['lang_passport']['newpwd'] = "输入新密码";
$GLOBALS['gLang']['lang_passport']['newpwd2'] = "再次输入密码";
$GLOBALS['gLang']['lang_passport']['insertyouranswer'] = "请输入您的答案";
$GLOBALS['gLang']['lang_passport']['pwdrule'] = "密码长度要大于6位";
$GLOBALS['gLang']['lang_passport']['coderule'] = "请输入验证码";
$GLOBALS['gLang']['lang_passport']['realnamerule'] = "请输入真实姓名";

$GLOBALS['gLang']['lang_passport']['pwdreset'] = "祝贺！您的密码已经更新成功。";
$GLOBALS['gLang']['lang_passport']['failture'] = "失败！请重试。";
$GLOBALS['gLang']['lang_passport']['answerwrong'] = "对不起！答案错误。";
$GLOBALS['gLang']['lang_passport']['emailsent'] = "邮件已经发送！请查收。";
$GLOBALS['gLang']['lang_passport']['emailsendok'] = "祝贺！发送成功。";
$GLOBALS['gLang']['lang_passport']['emailsubject'] = "找回密码";
$GLOBALS['gLang']['lang_passport']['emailcontent'] = '亲爱的 &lt; %s &gt; ：<br>
				 您申请了找回密码服务! 请点击下面的地址，然后重置您的密码。此地址60分钟后失效。<br>%s<br>%s';

$GLOBALS['gLang']['lang_global']['web-title'] = "欢迎使用&quot;Xppass&quot;单点登录系统";
$GLOBALS['gLang']['lang_global']['menu1'] = '首页';
$GLOBALS['gLang']['lang_global']['menu2'] = '登录';
$GLOBALS['gLang']['lang_global']['menu3'] = '注册新用户';
$GLOBALS['gLang']['lang_global']['menu4'] = '系统管理';
$GLOBALS['gLang']['lang_global']['menu5'] = '帮助';
$GLOBALS['gLang']['lang_global']['selectlanguage'] = '选择语言';
$GLOBALS['gLang']['lang_global']['zh-cn'] = '简体中文';
$GLOBALS['gLang']['lang_global']['zh-tw'] = '繁体中文';
$GLOBALS['gLang']['lang_global']['en'] = '英文';

$GLOBALS['gLang']['lang_install']['new_step'] = '下一步';
$GLOBALS['gLang']['lang_install']['old_step'] = '上一步';
$GLOBALS['gLang']['lang_install']['not_continue'] = '请将以上红叉部分修正再试';


?>